### ISSUE TITLE
TopIndex

### ISSUE THREAD

**Issue by lisasit** [woywoy123/AnalysisG#3]
event.Tops[child.TopIndex] is not the same top as child.Parent[0] (or event.Tops[truthjet.TopIndex[0]] is not the same as truthjet.Tops[0] even when the truthjet is matched to only one top)

**Comment by eleboulicaut** [comment]
Adding on to this, I wrote a short script which demonstrates this problem. It's in `truth-studies/BaseLineTruthAnalysis/TestFromRes.py`. I get exact opposite results for the FromRes variable if I loop over `event.TopChildren` then do `event.Tops[p.TopIndex].FromRes` vs looping over `event.Tops` then doing `t.FromRes`.

**Comment by woywoy123** [comment]
Will work on resolving this asap

**Comment by woywoy123** [comment]
Ok I managed to fix the issue. Thanks @eleboulicaut for writing the example code. 

Although I found that this wasn't really a bug. When accessing `event.Tops[p.TopIndex]` you have to keep in mind that `event.Tops` is a list and not a dictionary. The way the tops are sorted is by descending order here is an example:

Accessing top.index [3, 2, 1, 0]
Accessing top.FromRes [1, 1, 0, 0]
Accessing child.TopIndex from tops.Children [[3, 3, 3], [2, 2, 2], [1, 1, 1], [0, 0, 0]]
Accessing child.TopIndex from Event.TopChildren [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]
Using child.TopIndex as an index to access list [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]]

To fix the issue, the `event.Tops` and `event.TopChildren` lists needed to be reversed. 

Accessing top.index [0, 1, 2, 3]
Accessing top.FromRes [0, 0, 1, 1]
Accessing child.TopIndex from tops.Children [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]]
Accessing child.TopIndex from Event.TopChildren [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]
Using child.TopIndex as an index to access list [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]]

I have updated the code to reflect the latter convention, since it does make more sense to have it organized in such a way.
