### ISSUE TITLE
Number of neutrino solutions

### ISSUE THREAD

**Issue by eleboulicaut** [woywoy123/AnalysisG#6]
When comparing different implementations of the neutrino reconstruction algorithm, we found different numbers of events. 
This is demonstrated in the script `models/NeutrinoReconstruction/DoubleNeutrino_noROOT_2methods.py` ([here](https://github.com/woywoy123/AnalysisTopGNN/blob/dev_elise/models/NeutrinoReconstruction/DoubleNeutrino_noROOT_2methods.py) in my branch dev_elise), which I modified from `DoubleNeutrino.py`.
It compares the PyTorch implementation with the original implementation from the paper except using python3 and no ROOT (found in `NeutrinoReconstructionOriginal/neutrino_momentum_reconstruction.py` on dev_elise). 
The plots for pT, E, phi, eta, and mass all show good agreement but the plot for number of neutrino solutions shows a large difference (see below). 
It's possible the difference could come from an increased precision when using the PyTorch implementation, but I would expect this difference to be relatively small. I also find it strange that the PyTorch approach always yields 4 solutions. Any ideas on this?
![NumNeutrinoSolutions](https://user-images.githubusercontent.com/50581372/219181050-098c1dcb-cdea-4868-a922-d16e7556bada.png)

**Comment by woywoy123** [comment]
Ok so I think I fixed the issue with the latest neutrino reconstruction code. You might wonder why there are no 1 solution cases in my figure. I deactivated the leastsq segment of the original neutrino reconstruction code, because I havnt implemented this in the Torch version. This might be something to work on in the future. So far the PyTorch code seems consistent. See code [here](https://github.com/woywoy123/AnalysisTopGNN/blob/master/truth-studies/NeutrinoReconstruction/DoubleNeutrinoComparison.py).

```python 
        if not v and leastsq:
            es = [ss.H_perp for ss in self.solutionSets]
            met = np.array([metX, metY, 1])

            def nus(ts):
                return tuple(e.dot([math.cos(t), math.sin(t), 1])
                             for e, t in zip(es, ts))

            def residuals(params):
                return sum(nus(params), -met)[:2]

            ts,_ = leastsq(residuals, [0, 0],
                           ftol=5e-5, epsfcn=0.01)
            v, v_ = [[i] for i in nus(ts)]
            
``` 
- Number of solutions:
![NumNeutrinoSolutions](https://user-images.githubusercontent.com/33817290/220368762-28284e94-10d3-4268-94d5-0c911ec6a296.png)

- Top Reconstruction from Truth Children and using the event Met, which should have detector inefficiencies. 
![Reconstructed_Top2_Mass](https://user-images.githubusercontent.com/33817290/220370462-bdb14391-75fe-46ef-a285-124a3d508083.png)
![Reconstructed_Top1_Mass](https://user-images.githubusercontent.com/33817290/220370470-daa3731f-71a6-4330-bafe-afd3c5e9f80a.png)

**Comment by woywoy123** [comment]
![Reconstructed_Top2_Mass](https://user-images.githubusercontent.com/33817290/220706747-3707e1ee-13fe-4e92-ad63-201af5c5d9b0.png)
![Reconstructed_Top1_Mass](https://user-images.githubusercontent.com/33817290/220706758-954f8774-939e-49b4-8f10-9a66aa63160f.png)
![NumNeutrinoSolutions](https://user-images.githubusercontent.com/33817290/220706761-ccc25879-3e79-4a1f-a154-72ce83e3cf0c.png)
![Chi2_Neutrino_Solutions](https://user-images.githubusercontent.com/33817290/220706765-22d17a5b-4511-4955-b220-a40da52693b4.png)


Adding figures for the record.
